services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: absolute_cinema
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./absolutecinema/.env
    volumes:
      - ./absolutecinema/.env:/app/.env
      - ./absolutecinema/resources:/app/absolutecinema/resources
