services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${AC_DATABASE_USER}
      POSTGRES_PASSWORD: ${AC_DATABASE_PASSWORD}
      POSTGRES_DB: ${AC_DATABASE_NAME}
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
