openapi: 3.0.0
info:
  title: Cinema Seat API
  version: 1.0.0

paths:
  /seats/:
    post:
      summary: Create a new seat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSeatInput"
      responses:
        "201":
          description: Seat created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SeatOutput"
        "400":
          description: Invalid input

  /seats/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: Get seat by ID
      responses:
        "200":
          description: Seat details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SeatOutput"
        "400":
          description: Invalid seat ID
        "404":
          description: Seat not found

    put:
      summary: Update a seat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateSeatInput"
      responses:
        "200":
          description: Seat updated successfully
        "400":
          description: Invalid input

    delete:
      summary: Delete a seat by ID
      responses:
        "204":
          description: Seat deleted successfully
        "400":
          description: Invalid seat ID
        "404":
          description: Seat not found

  /seats/room/{roomID}:
    parameters:
      - name: roomID
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: Get seats by Room ID
      responses:
        "200":
          description: List of seats
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SeatOutput"
        "400":
          description: Invalid room ID
        "404":
          description: Room not found

components:
  schemas:
    CreateSeatInput:
      type: object
      required:
        - roomID
        - row
        - number
      properties:
        roomID:
          type: string
          format: uuid
        row:
          type: string
          description: Seat row label
        number:
          type: integer
          minimum: 1
          description: Seat number in the row

    UpdateSeatInput:
      type: object
      required:
        - id
        - row
        - number
      properties:
        id:
          type: string
          format: uuid
        row:
          type: string
        number:
          type: integer
          minimum: 1

    SeatOutput:
      type: object
      properties:
        id:
          type: string
          format: uuid
        roomID:
          type: string
          format: uuid
        row:
          type: string
        number:
          type: integer
